import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Database, Shield } from 'lucide-react';
import { FOUNDATION, slug } from '@/data/siteData';
import { PHASE0 } from '@/config/phase0';
import { getFoundationStatus } from '@/contracts/client';
import { DemoNotice } from './DemoNotice';

const sections = ['Overview','Permissions','Delegation','Providers','Migration','Identity and retention','Scenarios'];
export default function FoundationPage() {
  const { sectionId } = useParams();
  const section = sections.find((s) => slug(s) === sectionId) || 'Overview';
  const [role,setRole] = useState('subcontractor');
  const [resource,setResource] = useState('restricted_document');
  const [connection,setConnection] = useState('Checking read-only contract service…');
  useEffect(() => { let mounted=true; getFoundationStatus().then((s) => {if(mounted)setConnection(`Contract service ${s.version} · live execution disabled`);}).catch(() => {if(mounted)setConnection('Contract service unavailable; local generated fixtures remain visible');}); return () => {mounted=false;}; }, []);
  if (!PHASE0.seedsEnabled) return <main className="min-h-screen bg-obsidian p-10 text-linen" data-testid="foundation-disabled"><h1 className="font-heading text-4xl">Contract previews disabled</h1><Link to="/" data-testid="foundation-disabled-home">Return home</Link></main>;
  const matrix = FOUNDATION.permissions;
  return <main className="min-h-screen bg-obsidian text-linen" data-testid="foundation-page"><header className="border-b border-white/20"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-6 sm:px-8"><Link to="/" className="flex items-center gap-2 text-sm" data-testid="foundation-home-link"><ArrowLeft size={16} />HawkVision Homes</Link><Link to="/perchpoint" className="flex items-center gap-2 text-sm text-gold" data-testid="foundation-workspace-link">Workspace previews <ArrowUpRight size={16} /></Link></div></header>
    <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><DemoNotice id="foundation-demo-notice" className="text-xs text-gold">Phase 0 · contract version {FOUNDATION.version} · synthetic data only</DemoNotice><h1 className="mt-5 font-heading text-4xl font-bold sm:text-5xl">Foundation review</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-linen/75">PerchPoint — HawkVision Homes Property Operations. Canonical records and policy contracts, without live identity, financial or screening workflows.</p><p className="mt-4 text-xs text-gold" role="status" data-testid="foundation-service-status">{connection}</p>
      <nav className="my-8 flex flex-wrap gap-x-6 gap-y-2 border-y border-white/20 py-3" aria-label="Foundation sections">{sections.map((s) => <Link key={s} to={`/foundation/${slug(s)}`} aria-current={section===s?'page':undefined} className={`border-b-2 py-3 text-sm ${section===s?'border-gold text-gold':'border-transparent text-linen/75'}`} data-testid={`foundation-tab-${slug(s)}`}>{s}</Link>)}</nav>
      <h2 className="mb-6 font-heading text-2xl" data-testid="foundation-section-heading">{section}</h2>
      {section==='Overview' && <div className="grid gap-10 md:grid-cols-2"><div><Database className="text-gold" /><h3 className="mt-5 font-heading text-xl">Canonical, not provider-owned</h3><p className="mt-4 text-sm leading-7 text-linen/75">Organization → ownership entity → property → building → unit. Shared spaces and assets attach to their actual location, not a fabricated unit.</p><dl className="mt-6 grid grid-cols-2 gap-5">{['properties','buildings','units','shared_spaces','assets'].map((k) => <div key={k} data-testid={`foundation-count-${k}`}><dt className="text-xs text-linen/75">{k.replaceAll('_',' ')}</dt><dd className="mt-2 font-heading text-3xl">{FOUNDATION.portfolio[k].length}</dd></div>)}</dl></div><div><Shield className="text-gold" /><h3 className="mt-5 font-heading text-xl">Explicit boundaries</h3><ul className="mt-4 space-y-4 text-sm leading-7 text-linen/75"><li>Stable UUIDs belong to PerchPoint; provider IDs belong to mapping records.</li><li>People, accounts and relationships remain distinct across move-out and role changes.</li><li>Future authorization requires server checks and directly tested PostgreSQL row-level security.</li><li>No live providers, MFA, approvals, payment postings or screening decisions are implemented.</li></ul></div></div>}
      {section==='Permissions' && <><div className="mb-7 grid gap-4 sm:grid-cols-2">{[['Role',role,setRole,matrix.roles],['Resource',resource,setResource,matrix.resources]].map(([label,value,setter,options]) => <label key={label} className="grid gap-2 text-sm">{label}<select className="h-11 border border-white/40 bg-obsidian px-3" value={value} onChange={(e) => setter(e.target.value)} data-testid={`matrix-${label.toLowerCase()}-select`}>{options.map((o) => <option key={o}>{o}</option>)}</select></label>)}</div><div className="grid gap-x-8 md:grid-cols-2">{matrix.actions.map((action) => {const rule=matrix.allow_rules.find((r) => r.role===role&&r.resource===resource&&r.action===action);return <div key={action} className="border-t border-white/20 py-4" data-testid={`matrix-action-${action}`}><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{action.replaceAll('_',' ')}</strong><span className={rule?'text-gold':'text-red-300'}>{rule?'Conditional contract grant':'Deny by default'}</span></div>{rule&&<p className="mt-3 text-xs leading-6 text-linen/75">Same organization; authorized ownership/property/building/unit scope. Household: {rule.household_scope}. Assignment: {rule.assignment_scope}. Sensitivity: {rule.record_sensitivity.join(', ')}. Audit: required. Reason: {rule.reason_required?'required':'action-dependent'}. Approval: {rule.approval_required?'required':'not required'}. Delegation: {rule.delegation_eligible?'eligible':'not eligible'}.</p>}</div>;})}</div><p className="mt-6 text-sm text-gold" data-testid="matrix-enforcement-disclosure">Specification only. UI visibility is not server authorization or RLS.</p></>}
      {section==='Delegation' && <><p className="mb-6 text-sm text-gold" data-testid="delegation-approval-warning">Configurable seeded examples. Farouk has not approved the $250 staff / $500 parts thresholds.</p><div className="grid gap-6 md:grid-cols-2">{FOUNDATION.scenarios.slice(0,4).map((s,i) => <article key={s.name} className="border-t border-white/20 py-5" data-testid={`delegation-scenario-${i}`}><h3 className="font-semibold">{s.name}</h3><p className="mt-3 text-sm text-gold">{s.actual}</p><p className="mt-3 text-sm leading-6 text-linen/75">{s.detail.reasons.join(' · ')}</p><p className="mt-2 text-xs text-linen/75">Execution: disabled{ s.detail.notification_required ? ' · immediate notification and retrospective review required (not sent)' : ''}</p></article>)}</div></>}
      {section==='Providers' && <div className="grid gap-x-8 md:grid-cols-2">{FOUNDATION.integrations.map((p) => <article key={p.id} className="border-t border-white/20 py-6" data-testid={`provider-${p.provider_type}`}><h3 className="font-heading text-xl">{p.provider_type.replaceAll('_',' ')}</h3><p className="mt-3 text-sm text-gold">Disconnected · not configured</p><p className="mt-3 text-sm text-linen/75">{p.provider_name}</p><p className="mt-3 text-xs leading-6 text-linen/75">No credential reference. No execution. Activation requires explicit approval, legal review and tested server access.</p></article>)}</div>}
      {section==='Migration' && <><p className="text-sm leading-7 text-linen/75">Synthetic Innago import, staged only. No imported canonical records or database writes. Existing tools are migration sources to retire after reconciled cutover—not permanent parallel systems.</p><div className="my-7 grid grid-cols-2 gap-5 md:grid-cols-4">{['observed_rows','valid_rows','duplicate_rows','rejected_rows'].map((k) => <div key={k} data-testid={`migration-total-${k}`}><p className="text-xs text-linen/75">{k.replaceAll('_',' ')}</p><p className="mt-2 font-heading text-3xl">{FOUNDATION.migration.control_totals[k]}</p></div>)}</div>{FOUNDATION.migration.rows.map((r) => <div className="border-t border-white/20 py-4" key={r.row_number} data-testid={`migration-row-${r.row_number}`}><p className="text-sm font-semibold">Row {r.row_number} · {r.source_record_identifier} · <span className="text-gold">{r.validation_result}</span></p><p className="mt-2 text-sm text-linen/75">{r.issues.join(' · ')||'Valid staging row; canonical import still requires approval.'}</p></div>)}<p className="mt-6 text-sm text-gold" data-testid="migration-reconciliation-status">Financial and document-count reconciliation require review.</p></>}
      {section==='Identity and retention' && <div className="grid gap-10 lg:grid-cols-2"><div><h3 className="font-heading text-xl">Identity lifecycle contracts</h3>{FOUNDATION.identity.map((i) => <details className="border-b border-white/20 py-4" key={i.operation}><summary className="cursor-pointer text-sm" data-testid={`identity-contract-${i.operation}`}>{i.operation.replaceAll('_',' ')}</summary><p className="mt-3 text-sm leading-7 text-linen/75">{i.preconditions.join(' · ')}. Not implemented. Time limits pending approval.</p></details>)}</div><div><h3 className="font-heading text-xl">Document classes & retention</h3><p className="mt-4 text-sm leading-7 text-gold">No final legal periods are invented. Qualified legal review is required; legal holds override deletion.</p>{FOUNDATION.retention.map((r) => <p className="border-b border-white/20 py-4 text-sm text-linen/75" key={r.id} data-testid={`retention-${r.document_class}`}>{r.document_class.replaceAll('_',' ')} · period unset</p>)}</div></div>}
      {section==='Scenarios' && <div>{FOUNDATION.scenarios.map((s,i) => <div key={s.name} className="flex flex-wrap justify-between gap-3 border-b border-white/20 py-4 text-sm" data-testid={`foundation-scenario-${i}`}><strong>{s.name}</strong><span className="text-gold">Expected: {String(s.expected)} · simulated: {String(s.actual)}</span></div>)}</div>}
    </div>
  </main>;
}