import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Building2, DoorOpen, Landmark, Layers3 } from 'lucide-react';
import { PORTFOLIO, ALL_UNITS, plural } from '@/data/siteData';
import { PHASE0 } from '@/config/phase0';
import { DemoNotice } from './DemoNotice';

const Node = ({ icon: Icon, label, value, testId }) => <div className="flex min-w-0 items-start gap-4 border-b border-white/20 py-4" data-testid={testId}><Icon className="mt-1 h-5 w-5 shrink-0 text-gold" /><span><span className="block text-xs text-linen/75">{label}</span><span className="mt-1 block text-sm font-semibold">{value}</span></span></div>;
export const PropertyHierarchyView = () => {
  const [propertyId, setPropertyId] = useState(PORTFOLIO.properties[0].id);
  const property = PORTFOLIO.properties.find((p) => p.id === propertyId);
  const owner = PORTFOLIO.ownership_entities.find((o) => o.id === property.ownership_entity_id);
  return <section id="properties" className="bg-obsidian py-24 text-linen sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]">
    <div><p className="kicker-line font-mono text-xs uppercase text-gold">Properties</p><h2 className="mt-5 font-heading text-4xl font-bold leading-tight sm:text-5xl">One site.<br />Every space accounted for.</h2><p className="mt-6 leading-8 text-linen/75">From a single home to a multi-building property. Residential units, business spaces, shared places and maintainable assets each have a distinct place.</p><p className="mt-6 border-l-2 border-copper pl-5 text-sm leading-7 text-linen/75">Cincinnati is our starting point—not a limit on where a property can belong.</p></div>
    {PHASE0.seedsEnabled ? <div data-testid="property-hierarchy-view"><DemoNotice id="hierarchy-demo-notice" className="text-xs text-gold" /><label className="mt-6 grid gap-2 text-sm">Example property<select className="min-h-12 max-w-full border border-white/40 bg-obsidian px-3" value={propertyId} onChange={(e) => setPropertyId(e.target.value)} data-testid="hierarchy-property-select">{PORTFOLIO.properties.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
      <Node icon={Landmark} label="Organization" value="HawkVision Homes — synthetic organization" testId="hierarchy-organization" /><Node icon={Layers3} label="Ownership entity" value={owner.legal_name} testId="hierarchy-ownership-entity" /><Node icon={Building2} label="Property" value={`${property.name} · ${property.address.municipality}, ${property.address.state}`} testId="hierarchy-property" />
      {PORTFOLIO.buildings.filter((b) => b.property_id === propertyId).map((b) => <div key={b.id} className="mt-4 border-l border-copper pl-5" data-testid={`hierarchy-building-${b.id}`}><Node icon={Building2} label="Building" value={b.name} testId={`building-name-${b.id}`} /><div className="divide-y divide-white/20">{ALL_UNITS.filter((u) => u.buildingId === b.id).map((u) => <Link to={`/rentals/${u.id}`} key={u.id} className="flex flex-wrap items-center justify-between gap-3 py-4 text-sm transition-colors hover:text-gold" data-testid={`unit-row-${u.id}`}><span className="flex items-center gap-2"><DoorOpen size={16} />{u.unit} · {u.use}</span><span>{u.use === 'Commercial' ? u.commercial.intended_use : `${plural(u.beds,'bed')} · ${plural(u.baths,'bath')}`}</span><span className="text-xs">{u.available}</span></Link>)}</div></div>)}
      <div className="mt-6 grid gap-6 border-t border-white/20 pt-6 sm:grid-cols-2" data-testid="hierarchy-shared-assets"><div><h3 className="text-sm font-semibold text-gold">Shared spaces</h3><ul className="mt-3 space-y-2 text-sm text-linen/75">{PORTFOLIO.shared_spaces.filter((s) => s.property_id === propertyId).map((s) => <li key={s.id} data-testid={`shared-space-${s.id}`}>{s.name}</li>)}</ul></div><div><h3 className="text-sm font-semibold text-gold">Assets</h3><ul className="mt-3 space-y-2 text-sm text-linen/75">{PORTFOLIO.assets.filter((s) => s.property_id === propertyId).map((s) => <li key={s.id} data-testid={`asset-${s.id}`}>{s.name}</li>)}</ul></div></div>
    </div> : <p data-testid="hierarchy-unpublished-state">Verified property information will appear here when published.</p>}
  </div></section>;
};